('JOS',   1,   1, 'After the death of Moses the servant of TheIAM<H3068>, TheIAM<H3068> spoke to Joshua the son of Nun, Moses\' servant, saying,'),
('JOS',   1,   2, '\"Moses my servant is dead. So arise, go across this Jordan, you and all these people, to the land I\'m giving them, even to the children of Israel.'),
('JOS',   1,   3, 'I have given you every place that the sole of your foot will tread on, as I told Moses.'),
('JOS',   1,   4, 'From the wilderness and this Lebanon even to the great river, the river Euphrates, all the land of the Hittites, and to the great sea toward the going down of the sun, shall be your border.'),
('JOS',   1,   5, 'No man will be able to stand before you all the days of your life. As I was with Moses, so I will be with you. I will not fail you nor forsake you.'),
('JOS',   1,   6, '\"Be strong and courageous; for you shall cause this people to inherit the land which I swore to their fathers to give them.'),
('JOS',   1,   7, 'Only be strong and courageous! Be very careful to obey all of the law that Moses my servant gave you. Don\'t turn from it to the right or to the left, that you may have good success wherever you go.'),
('JOS',   1,   8, 'This book of the law shall not depart from your mouth, but you shall meditate on it day and night, that you may observe to do according to all that is written in it; for then you shall make your way prosperous, and then you shall have good success.'),
('JOS',   1,   9, 'Haven\'t I commanded you? Be strong and courageous. Don\'t be afraid. Don\'t be dismayed. For TheIAM<H3068> your God<H0430> is with you wherever you go.\"'),
('JOS',   1,  10, 'Then Joshua commanded the officers of the people, saying,'),
('JOS',   1,  11, '\"Pass through the middle of the camp, and command the people, saying, \'Prepare food; for within three days you are to pass over this Jordan, to go in to possess the land which TheIAM<H3068> your God<H0430> is giving you to possess.\'\"'),
('JOS',   1,  12, 'Joshua spoke to the Reubenites, and to the Gadites, and to the half-tribe of Manasseh, saying,'),
('JOS',   1,  13, '\"Remember the word which Moses the servant of TheIAM<H3068> commanded you, saying, \'TheIAM<H3068> your God<H0430> gives you rest, and will give you this land.'),
('JOS',   1,  14, 'Your wives, your little ones, and your livestock shall live in the land which Moses gave you beyond the Jordan; but you shall pass over before your brothers armed, all the mighty men of valor, and shall help them'),
('JOS',   1,  15, 'until TheIAM<H3068> has given your brothers rest, as he has given you, and they have also possessed the land which TheIAM<H3068> your God<H0430> gives them. Then you shall return to the land of your possession and possess it, which Moses the servant of TheIAM<H3068> gave you beyond the Jordan toward the sunrise.\'\"'),
('JOS',   1,  16, 'They answered Joshua, saying, \"All that you have commanded us we will do, and wherever you send us we will go.'),
('JOS',   1,  17, 'Just as we listened to Moses in all things, so we will listen to you. Only may TheIAM<H3068> your God<H0430> be with you, as he was with Moses.'),
('JOS',   1,  18, 'Whoever rebels against your commandment, and doesn\'t listen to your words in all that you command him, he shall be put to death. Only be strong and courageous.\"'),
('JOS',   2,   1, 'Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, \"Go, view the land, including Jericho.\" They went and came into the house of a prostitute whose name was Rahab, and slept there.'),
('JOS',   2,   2, 'The king of Jericho was told, \"Behold, men of the children of Israel came in here tonight to spy out the land.\"'),
('JOS',   2,   3, 'The king of Jericho sent to Rahab, saying, \"Bring out the men who have come to you, who have entered into your house; for they have come to spy out all the land.\"'),
('JOS',   2,   4, 'The woman took the two men and hid them. Then she said, \"Yes, the men came to me, but I didn\'t know where they came from.'),
('JOS',   2,   5, 'About the time of the shutting of the gate, when it was dark, the men went out. Where the men went, I don\'t know. Pursue<H7291> them quickly; you may catch up with them.\"'),
('JOS',   2,   6, 'But she had brought them up to the roof, and hidden them under the stalks of flax which she had laid in order on the roof.'),
('JOS',   2,   7, 'The men pursued<H7291> them along the way to the fords of the Jordan. As soon as those who pursued them had gone out, they shut the gate.'),
