INSERT INTO `verses` (`bookCode`, `chapter`, `verseNumber`, `verseText`) VALUES
('RUT',   1,   1, 'In the days when the judges judged, there was a famine in the land. A certain man of Bethlehem Judah went to live in the country of Moab with his wife and his two sons.'),
('RUT',   1,   2, 'The name of the man was Elimelech, and the name of his wife Naomi. The names of his two sons were Mahlon and Chilion, Ephrathites of Bethlehem Judah. They came into the country of Moab and lived there.'),
('RUT',   1,   3, 'Elimelech, Naomi\'s husband, died; and she was left with her two sons.'),
('RUT',   1,   4, 'They took for themselves wives of the women of Moab. The name of the one was Orpah, and the name of the other was Ruth. They lived there about ten years.'),
('RUT',   1,   5, 'Mahlon and Chilion both died, and the woman was bereaved of her two children and of her husband.'),
('RUT',   1,   6, 'Then she arose with her daughters-in-law, that she might return from the country of Moab; for she had heard in the country of Moab how TheIAM<H3068> had visited his people in giving them bread.'),
('RUT',   1,   7, 'She left the place where she was with her two daughters-in-law, and they went on the way to return to the land of Judah.'),
('RUT',   1,   8, 'Naomi said to her two daughters-in-law, \"Go, return each of you to your mother\'s house. May TheIAM<H3068> deal kindly with you, as you have dealt with the dead and with me.'),
('RUT',   1,   9, 'May TheIAM<H3068> grant you that you may find rest, each of you in the house of her husband.\" Then she kissed them, and they lifted up their voices, and wept.'),
('RUT',   1,  10, 'They said to her, \"No, but we will return with you to your people.\"'),
('RUT',   1,  11, 'Naomi said, \"Go back, my daughters. Why do you want to go with me? Do I still have sons in my womb, that they may be your husbands?'),
('RUT',   1,  12, 'Go back, my daughters, go your way; for I am too old to have a husband. If I should say, \'I have hope,\' if I should even have a husband tonight, and should also bear sons,'),
('RUT',   1,  13, 'would you then wait until they were grown? Would you then refrain from having husbands? No, my daughters, I am seriously grieved for your sakes, since the hand of TheIAM<H3068> has gone out against me.\"'),
('RUT',   1,  14, 'They lifted up their voices and wept again; then Orpah kissed her mother-in-law, but Ruth stayed with her.'),
('RUT',   1,  15, 'She said, \"Behold, your sister-in-law has gone back to her people and to her gods<H0430>. Follow your sister-in-law.\"'),
('RUT',   1,  16, 'Ruth said, \"Don\'t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God<H0430> my God<H0430>.'),
('RUT',   1,  17, 'Where you die, I will die, and there I will be buried. May TheIAM<H3068> so deal with me, and even more, if anything but death parts you and me.\"'),
('RUT',   1,  18, 'When she saw that she was determined to go with her, she stopped speaking.'),







('MAL',   1,   1, 'A revelation, TheIAM<H3068>\'s word to Israel by Malachi.'),
('MAL',   1,   2, '\"I have loved you,\" says TheIAM<H3068>. Yet you say, \"How have you loved us?\" \"Wasn\'t Esau Jacob\'s brother?\" says TheIAM<H3068>, \"Yet I loved Jacob;'),
('MAL',   1,   3, 'but Esau I hated, and made his mountains a desolation, and gave his heritage to the jackals of the wilderness.\"'),
('MAL',   1,   4, 'Whereas Edom says, \"We are beaten down, but we will return and build the waste places;\" TheIAM<H3068> of Armies says, \"They shall build, but I will throw down; and men will call them \'The Wicked Land,\' even the people against whom TheIAM<H3068> shows wrath forever.\"'),
('MAL',   1,   5, 'Your eyes will see, and you will say, \"TheIAM<H3068> is great- even beyond the border of Israel!\"'),
('MAL',   1,   6, '\"A son honors his father, and a servant his master<H0113>. If I am a father, then where is my honor? And if I am a master<H0113>, where is the respect due me? Says TheIAM<H3068> of Armies to you, priests, who despise my name. You say, \'How have we despised your name?\''),
('MAL',   1,   7, 'You offer polluted bread on my altar. You say, \'How have we polluted you?\' In that you say, \'TheIAM<H3068>\'s table contemptible.\''),
('MAL',   1,   7, 'You offer polluted bread on my altar. You say, \'How have we polluted you?\' In that you say, \'TheIAM<H3068>\'s table is contemptible.\''),
('MAL',   1,   8, 'When you offer the blind for sacrifice, isn\'t that evil? And when you offer the lame and sick, isn\'t that evil? Present it now to your governor! Will he be pleased with you? Or will he accept your person?\" says TheIAM<H3068> of Armies.'),
('MAL',   1,   9, '\"Now, please entreat the favor of God<H0410>, that he may be gracious to us. With this, will he accept any of you?\" says TheIAM<H3068> of Armies.'),
('MAL',   1,  10, '\"Oh that there were one among you who would shut the doors, that you might not kindle fire on my altar in vain! I have no pleasure in you,\" says TheIAM<H3068> of Armies, \"neither will I accept an offering at your hand.'),
('MAL',   1,  11, 'For from the rising of the sun even to its going down, my name is great among the nations, and in every place incense will be offered to my name, and a pure offering: for my name is great among the nations,\" says TheIAM<H3068> of Armies.'),
('MAL',   1,  12, '\"But you profane it, in that you say, \'TheIAM<H3068>\'s table is polluted, and its fruit, even its food, is contemptible.\''),
('MAL',   1,  13, 'You say also, \'Behold, what a weariness it is!\' and you have sniffed at it\", says TheIAM<H3068> of Armies; \"and you have brought that which was taken by violence, the lame, and the sick; thus you bring the offering. Should I accept this at your hand?\" says TheIAM<H3068>.'),
('MAL',   1,  14, '\"But the deceiver is cursed, who has in his flock a male, and vows, and sacrifices to the Lord<H0136> a defective thing; for I am a great King,\" says TheIAM<H3068> of Armies, \"and my name is awesome among the nations.\"'),
('MAL',   2,   1, '\"Now, you priests, this commandment is for you.'),
('MAL',   2,   2, 'If you will not listen, and if you will not take it to heart, to give glory to my name,\" says TheIAM<H3068> of Armies, \"then I will send the curse on you, and I will curse your blessings. Indeed, I have cursed them already, because you do not take it to heart.'),
('MAL',   2,   3, 'Behold, I will rebuke your offspring, and will spread dung on your faces, even the dung of your feasts; and you will be taken away with it.'),
('MAL',   2,   4, 'You will know that I have sent this commandment to you, that my covenant may be with Levi,\" says TheIAM<H3068> of Armies.'),
('MAL',   2,   5, '\"My covenant was with him of life and peace; and I gave them to him that he might be reverent toward me; and he was reverent toward me, and stood in awe of my name.'),
('MAL',   2,   6, 'The law of truth was in his mouth, and unrighteousness was not found in his lips. He walked with me in peace and uprightness, and turned many away from iniquity.'),
('MAL',   2,   7, 'For the priest\'s lips should keep knowledge, and they should seek the law at his mouth; for he is the messenger of TheIAM<H3068> of Armies.'),
('MAL',   2,   8, 'But you have turned away from the path. You have caused many to stumble in the law. You have corrupted the covenant of Levi,\" says TheIAM<H3068> of Armies.'),
('MAL',   2,   9, '\"So I have also made you contemptible and low before all the people, according to the way you have not kept my ways, but have had respect for persons in the law.'),
('MAL',   2,   9, '\"Therefore I have also made you contemptible and wicked before all the people, according to the way you have not kept my ways, but have had respect for persons in the law.'),
('MAL',   2,  10, 'Don\'t we all have one father? Hasn\'t one God<H0410> created us? Why do we deal treacherously every man against his brother, profaning the covenant of our fathers?'),
('MAL',   2,  11, 'Judah has dealt treacherously, and an abomination is committed in Israel and in Jerusalem; for Judah has profaned the holiness of TheIAM<H3068> which he loves, and has married<H1166> the daughter of a foreign god<H0410>.'),
('MAL',   2,  12, 'TheIAM<H3068> will cut off, to the man who does this, him who wakes and him who answers, out of the tents of Jacob, and him who offers an offering to TheIAM<H3068> of Armies.'),
('MAL',   2,  13, 'This again you do: you cover TheIAM<H3068>\'s altar with tears, with weeping, and with sighing, because he doesn\'t regard the offering any more, neither receives it with good will at your hand.'),
('MAL',   2,  14, 'Yet you say, \'Why?\' Because TheIAM<H3068> has been witness between you and the wife of your youth, against whom you have dealt treacherously, though she is your companion, and the wife of your covenant.'),
('MAL',   2,  15, 'Did he not make you one, although he had the residue of the Spirit? Why one? He sought Godly<H0430> offspring. Therefore take heed to your spirit, and let no one deal treacherously against the wife of his youth.'),
('MAL',   2,  16, 'One who hates and divorces\", says TheIAM<H3068>, the God<H0430> of Israel, \"covers his garment with violence!\" says TheIAM<H3068> of Armies. \"Therefore pay attention to your spirit, that you don\'t be unfaithful.'),
('MAL',   2,  17, 'You have wearied TheIAM<H3068> with your words. Yet you say, \'How have we wearied him?\' In that you say, \'Everyone who does evil is good in TheIAM<H3068>\'s sight, and he delights in them;\' or \'Where is the God<H0430> of justice?\''),
('MAL',   3,   1, '\"Behold, I send my messenger, and he will prepare the way before me; and the Lord<H0113>, whom you seek, will suddenly come to his temple; and the messenger of the covenant, whom you desire, behold, he comes!\" says TheIAM<H3068> of Armies.'),
('MAL',   3,   2, '\"But who can endure the day of his coming? And who will stand when he appears? For he is like a refiner\'s fire, and like launderers\' soap;'),
('MAL',   3,   3, 'and he will sit as a refiner and purifier of silver, and he will purify the sons of Levi, and refine them as gold and silver; and they shall offer to TheIAM<H3068> offerings in righteousness.'),
('MAL',   3,   4, 'Then the offering of Judah and Jerusalem will be pleasant to TheIAM<H3068>, as in the days of old, and as in ancient years.'),
('MAL',   3,   5, 'I will come near to you to judgment; and I will be a swift witness against the sorcerers, and against the adulterers, and against the perjurers, and against those who oppress the hireling in his wages, the widow, and the fatherless, and who deprive the foreigner of justice, and don\'t fear me,\" says TheIAM<H3068> of Armies.'),
('MAL',   3,   6, '\"For I, TheIAM<H3068>, don\'t change; therefore you, sons of Jacob, are not consumed.'),
('MAL',   3,   7, 'From the days of your fathers you have turned away from my ordinances, and have not kept them. Return to me, and I will return to you,\" says TheIAM<H3068> of Armies. \"But you say, \'How shall we return?\''),
('MAL',   3,   8, 'Can man rob God<H0430>? Yet you rob me! But you say, \'How have we robbed you?\' In tithes and offerings.'),
('MAL',   3,   9, 'You are cursed with the curse; for you rob me, even this whole nation.'),
('MAL',   3,  10, 'Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this,\" says TheIAM<H3068> of Armies, \"if I will not open you the windows of heaven, and pour you out a blessing, that there will not be room enough for.'),
('MAL',   3,  11, 'I will rebuke the devourer for your sakes, and he shall not destroy the fruits of your ground; neither shall your vine cast its fruit before its time in the field,\" says TheIAM<H3068> of Armies.'),
('MAL',   3,  12, '\"All nations shall call you blessed, for you will be a delightful land,\" says TheIAM<H3068> of Armies.'),
('MAL',   3,  13, '\"Your words have been stout against me,\" says TheIAM<H3068>. \"Yet you say, \'What have we spoken against you?\''),
('MAL',   3,  14, 'You have said, \'It is vain to serve God<H0430>;\' and \'What profit is it that we have followed his instructions, and that we have walked mournfully before TheIAM<H3068> of Armies?'),
('MAL',   3,  15, 'Now we call the proud happy; yes, those who work wickedness are built up; yes, they tempt God<H0430>, and escape.\''),
('MAL',   3,  16, 'Then those who feared TheIAM<H3068> spoke one with another; and TheIAM<H3068> listened, and heard, and a book of memory was written before him, for those who feared TheIAM<H3068>, and who honored his name.'),
('MAL',   3,  17, 'They shall be mine,\" says TheIAM<H3068> of Armies, \"my own possession in the day that I make, and I will spare them, as a man spares his own son who serves him.'),
('MAL',   3,  18, 'Then you shall return and discern between the righteous and the wicked, between him who serves God<H0430> and him who doesn\'t serve him.'),
('MAL',   4,   1, '\"For, behold, the day comes, it burns as a furnace; and all the proud, and all who work wickedness, will be stubble; and the day that comes will burn them up,\" says TheIAM<H3068> of Armies, \"that it shall leave them neither root nor branch.'),
('MAL',   4,   2, 'But to you who fear my name shall the sun of righteousness arise with healing in its wings. You will go out, and leap like calves of the stall.'),
('MAL',   4,   3, 'You shall tread down the wicked; for they will be ashes under the soles of your feet in the day that I make,\" says TheIAM<H3068> of Armies.'),
('MAL',   4,   4, '\"Remember the law of Moses my servant, which I commanded to him in Horeb for all Israel, even statutes and ordinances.'),
('MAL',   4,   5, 'Behold, I will send you Elijah the prophet before the great and terrible day of TheIAM<H3068> comes.'),
('MAL',   4,   6, 'He will turn the hearts of the fathers to the children, and the hearts of the children to their fathers, lest I come and strike the earth with a curse.\"'),
